<script>
  const processFilters = [
    ['PATTERN', 'Keep groups whose identity or command contains this text'], ['--user USER', 'Keep processes owned by this username or UID'], ['--pid PID', 'Inspect one exact process ID'],
    ['--min-cpu PERCENT', 'Hide groups below this CPU percentage'], ['--min-memory SIZE', 'Hide groups below this amount of memory']
  ];
  const commonOutput = [['-n, --top N', 'Limit the number of groups shown'], ['-v, --verbose', 'Expand groups into processes, connections, or other details'], ['--json / --jsonl', 'Return pretty or compact machine-readable data'], ['--no-color', 'Disable color and terminal graphics']];

  const explanations = {
    cpu: ['See which applications are keeping the processors busy. pq samples Linux process data, groups related processes such as Chrome renderers or Gradle workers, and ranks those groups by CPU use.', 'Start with the command below, then add a name, owner, threshold, or display option only when you need it.'],
    memory: ['See which applications account for resident memory. Related processes are grouped together, so a multi-process application appears as one useful total instead of dozens of PIDs.', 'The normal report uses RSS. Use --pss when you need shared memory divided proportionally between processes.'],
    swap: ['Find the applications whose pages have been moved to swap. The report keeps resident memory visible alongside swap so you can judge the scale of each process group.', 'Filters and display options work the same way as the CPU and memory reports.'],
    net: ['See which processes are listening for connections or talking to peers. pq reads Linux socket tables and joins each socket back to its owning process.', 'A socket filter such as --port or --listen implies network mode, so pq --port 8080 is enough—you do not also need to write --net.'],
    io: ['Measure which processes are issuing read and write requests during a short sample. Choose combined I/O, reads, or writes, then narrow the result with ordinary process filters.', 'Socket filters also compose here: for example, --port 5432 --io measures I/O only for the processes that own that port.'],
    disk: ['See where space is used below a directory. dq scans once, then groups the matching files by directory, file, owner, or modification age.', 'Views, filters, accounting, and display options compose. For example, choose files, require an age and size, then ask for the top 30 results.'],
    files: ['Inspect files and descriptors that are still held by running processes. This can find descriptor pressure, deleted files that still consume disk space, or the process preventing a filesystem from being unmounted.', 'Path selectors compose with reports: --mount /mnt/data --fds counts descriptors only among processes holding that mount.']
  };

  const exampleLabels = {
    cpu: ['Only Chrome process groups', 'Top 20 processes owned by postgres', 'Chrome as a parent/child tree'],
    memory: ['Memory used by Chrome', 'Large PostgreSQL process groups', 'Detailed proportional memory for one PID'],
    swap: ['All swap users', 'Expanded details for Chrome', 'Large process groups, ranked by swap'],
    net: ['Find the owner of a local port', 'Public TCP listeners', 'Established connections to HTTPS peers'],
    io: ['I/O generated by PostgreSQL', 'Read rates for one user', 'Write rates for the owner of port 5432'],
    disk: ['Directory usage in a project folder', 'Old files larger than 1 GB', 'Ignore generated and cache directories'],
    files: ['Deleted files still using space', 'Descriptor counts for PostgreSQL', 'Detailed descriptor use beneath a mount']
  };

  const branches = {
    cpu: {
      label: 'CPU', command: 'pq --cpu', note: 'Processes grouped and ranked by CPU use.',
      groups: [['Filter', processFilters], ['Display', [['--tree', 'parent/child table'], ['--interval MS', 'sampling time'], ...commonOutput]], ['Other process reports', [['--blocked', 'blocked tasks'], ['--oom', 'OOM preference'], ['--limits', 'resource limits']]]],
      examples: ['pq --cpu chrome', 'pq --cpu --user postgres -n 20', 'pq --cpu --tree chrome']
    },
    memory: {
      label: 'Memory', command: 'pq --memory', note: 'Processes grouped and ranked by resident memory.',
      groups: [['Filter', processFilters], ['Display', [['--tree', 'parent/child table'], ['--interval MS', 'sampling time'], ...commonOutput]], ['Other memory reports', [['--pss', 'proportional memory'], ['--swap', 'swap use'], ['--oom', 'OOM preference'], ['--limits', 'resource limits']]]],
      examples: ['pq --memory chrome', 'pq --memory --user postgres --min-memory 500M', 'pq --pss --pid 1234']
    },
    swap: {
      label: 'Swap', command: 'pq --swap', note: 'Processes grouped and ranked by swap use.',
      groups: [['Filter', processFilters], ['Display', [['--tree', 'parent/child table'], ['--interval MS', 'sampling time'], ...commonOutput]], ['Related', [['--memory', 'resident memory'], ['--pss', 'proportional memory'], ['--oom', 'OOM preference']]]],
      examples: ['pq --swap', 'pq --swap chrome -v', 'pq --swap --min-memory 1GiB -n 20']
    },
    net: {
      label: 'Network', command: 'pq --net', note: 'Connections and listeners attributed to processes.',
      groups: [['Filter sockets', [['--port PORT', 'local port'], ['--remote-port PORT', 'peer port'], ['--listen', 'listeners only'], ['--tcp / --udp', 'protocol'], ['--state STATE', 'socket state'], ['--public', 'all-interface listeners']]], ['Filter processes', processFilters.slice(0, 3)], ['Display', [['--services', 'service names'], ['--resolve', 'resolve peers'], ...commonOutput]], ['Related', [['--unix [PATH]', 'Unix sockets'], ['--kill', 'stop socket owners']]]],
      examples: ['pq --port 8080', 'pq --net --listen --tcp --public', 'pq --remote-port 443 --state established -v']
    },
    io: {
      label: 'I/O', command: 'pq --io', note: 'Process read and write rates over a sample.',
      groups: [['Choose rate', [['--io', 'read + write'], ['--read', 'reads'], ['--write', 'writes']]], ['Filter processes', processFilters], ['Filter by socket owner', [['--port PORT', 'local port'], ['--remote-port PORT', 'peer port'], ['--listen', 'listeners']]], ['Display', [['--interval MS', 'sampling time'], ...commonOutput]]],
      examples: ['pq --io postgres', 'pq --read --user postgres', 'pq --port 5432 --write']
    },
    disk: {
      label: 'Disk', command: 'dq', note: 'Disk usage below a directory.',
      groups: [['Choose view', [['dq [DIR]', 'directories'], ['--files', 'largest files'], ['--owners', 'usage by owner'], ['--age', 'usage by age']]], ['Filter', [['--exclude PATTERN', 'exclude paths; repeatable'], ['--exclude-from FILE', 'patterns from file'], ['--older-than AGE', 'minimum age'], ['--min-size SIZE', 'minimum size']]], ['Count', [['--allocated', 'filesystem blocks'], ['--apparent', 'logical size'], ['--cross-filesystems', 'cross mounts']]], ['Display', [['--top N', 'number of rows'], ['--depth N', 'directory depth'], ['--min-percent PERCENT', 'hide small groups'], ['--all', 'show all'], ['--errors', 'unreadable paths'], ['--json / --jsonl', 'machine output']]]],
      examples: ['dq ~/Projects', 'dq --files --older-than 90d --min-size 1G /var', "dq --exclude node_modules --exclude '*.cache' ."]
    },
    files: {
      label: 'Open files', command: 'pq --fds', note: 'Files and descriptors held by running processes.',
      groups: [['Choose report', [['--fds', 'descriptor counts'], ['--deleted', 'deleted files consuming space'], ['--mount PATH', 'holders beneath a path'], ['--file PATH', 'holders of one path']]], ['Filter processes', processFilters.slice(0, 3)], ['Display', commonOutput]],
      examples: ['pq --deleted', 'pq --fds --user postgres', 'pq --mount /mnt/data --fds -v']
    }
  };

  let active = 'cpu';
  $: branch = branches[active];
</script>

<div class="branch-layout">
  <nav class="query-branches" aria-label="Choose a query">
    <p>What are you looking at?</p>
    {#each Object.entries(branches) as [key, item]}
      <button class:active={active === key} on:click={() => active = key}><span>{item.label}</span><code>{item.command}</code></button>
    {/each}
  </nav>

  <article class="branch-doc">
  <header class="branch-header">
    <h1>{branch.label}</h1>
    {#each explanations[active] as paragraph}<p>{paragraph}</p>{/each}
    <div class="branch-command"><span>Start with</span><code>$ {branch.command}</code></div>
  </header>

  <div class="compose-label"><span>Build on this query</span></div>
  <div class="option-groups">
    {#each branch.groups as group}
      <section>
        <h2>{group[0]}</h2>
        <dl>
          {#each group[1] as option}
            <div><dt><code>{option[0]}</code></dt><dd>{option[1]}</dd></div>
          {/each}
        </dl>
      </section>
    {/each}
  </div>

  <section class="branch-examples">
    <h2>Complete commands</h2>
    {#each branch.examples as example, index}<div><span>{exampleLabels[active][index]}</span><code>$ {example}</code></div>{/each}
  </section>
  </article>
</div>
